name: release
on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Perform a semantic release
    runs-on: ubuntu-latest
    steps:
      - name: action-release
        uses: mateothegreat/action-release@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          owner: mateothegreat
          repo: action-release
          increment: patch
